nameOverride: "xui"
fullnameOverride: "xui-panel"
# Image settings
image:
  repository: ghcr.io/mhsanaei/3x-ui
  pullPolicy: IfNotPresent
  tag: "latest"

# Host network settings (required for VPN protocols)
hostNetwork: true

# Environment variables (from docker-compose)
env:
  XRAY_VMESS_AEAD_FORCED: "false"
  XUI_ENABLE_FAIL2BAN: "true"

# Storage settings for SQLite (/etc/x-ui/)
persistence:
  enabled: true
  # Leave empty to use the default local-path provisioner in k3s
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# Application ports
service:
  type: ClusterIP
  panelPort: 2053
  subPort: 2096

# Ingress settings (Routing)
ingress:
  enabled: true
  className: "traefik" # Default ingress controller in k3s
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Specify your ClusterIssuer

  host: admin-panel.example.com
  tlsSecretName: 3xui-tls-secret # cert-manager will put tls.crt and tls.key in this secret

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}
tolerations: []
