apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "3xui.fullname" . }}
  labels:
    {{- include "3xui.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "3xui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "3xui.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ include "3xui.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true 
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: db-volume
              mountPath: /etc/x-ui/
            - name: cert-volume
              mountPath: /root/cert/
              readOnly: true
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: db-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "3xui.fullname" . }}-db
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: cert-volume
          secret:
            secretName: {{ .Values.ingress.tlsSecretName }}
            optional: true 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}